<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
     'ID' => 'ID Χρήστη',
     'Name' => 'Όνομα',
     'Descr' => 'Περιγραφή',
     'Type' => 'Τύπος',
     'Alias' => 'Alias',
     'App Key' => 'Κλειδί Εφαρμογής',
     'Vendor' => 'Προμηθευτής',
     'Vendor Email' => 'Email Προμηθευτή',
     'Version' => 'Έκδοση',
     'Active' => 'Ενεργή',
     'App Icon' => 'Εικονίδιο Εφαρμογής',
     'Created At' => 'Ημερομηνία Δημιουργίας',
     'Updated At' => 'Ημερομηνία Αλλαγής',
     'Uninstall' => 'Απεγκατάσταση',
     'Reload App Defaults' => 'Επαναφόρτωση αρχικοποιημένες τιμές  Εφαρμογής',
     'Reload App Permissions' => 'Επαναφόρτωση Προσβάσεων Εφαρμογής',
     'Reload App Settings' => 'Επαναφόρτωση Ρυθμίσεων Εφαρμογής',
     'Reload App Tables' => 'Επαναφόρτωση Πινάκων Δεδομένων Εφαρμογής',
     'List of Applications' => 'Λίστα Εφαρμογών',
     'Install new App' => 'Εγκατάσταση νέας Εφαρμογής',
     'File' => 'Αρχείο',
     'Install' => 'Εγκατάσταση',
     'Settings' => 'Ρυθμίσεις',
     'More' => 'Περισσότερα',
     'Deactivate' => 'Απενεργοποίηση',
     'Are you sure you want to Deactivate application ?' => 'Είσαι σίγουρος πως θέλεις την Απενεργοποίηση της εφαρμογής ?',
   
];
